### ISSUE TITLE
Limit all results to selected OUs

### ISSUE THREAD

**Issue by P3N-101** [MRSCompanyLtd/SPFX-Staff-Directory#1]
Hi, is it possible to limit the results to a number of OU's, using the departments but want to limit the display results from a number of OUs otherwise we get all the generic/service accounts shown which we would like to suppress...

Can it be done in the appended search query?

**Comment by dperk6** [comment]
Thanks for using this! You can definitely do it in the appended search query. However, you'll need to map the field to a SharePoint managed property for a user first. Here is a great blog post from Sharegate on how to do that if you need more info: https://sharegate.com/blog/filtering-content-with-sharepoint-user-properties-search. Then you can append it with a standard SP search query (i.e. AND (MappedProperty=DesiredOU*) ). Note that the search crawling on SharePoint Online doesn't happen regularly so it might take a while to reflect your new mapped property.

Let us know how it goes.

**Comment by P3N-101** [comment]
Thanks for the quick response....we are using it on a rather large client 100,000+ users, 15 orgs.. and want to limit it as you can imagine so much stuff comes back that's not useful....
I will give it a go and let you know.
