### ISSUE TITLE
When deploying on Sharepoint it gives an error

### ISSUE THREAD

**Issue by cerberuscgn** [MRSCompanyLtd/spfx-staff-directory#4]
Thank you so much for this project.
I am having a little issues when building and deploying. 
Locally everything works fine, but when deploying on sharepoint, the webpart failes with this error.

Something went wrong
If the problem persists, contact the site administrator and give them the information in Technical Details.
TECHNICAL DETAILS
ERROR:
Cannot read properties of undefined (reading 'id')

CALL STACK:
TypeError: Cannot read properties of undefined (reading 'id')
    at https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_b579cd4edfb4a2fae3bb11eb75f7824c.js:197:10988
    at new Promise (<anonymous>)
    at e.loadComponent (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_b579cd4edfb4a2fae3bb11eb75f7824c.js:197:10956)
    at https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_b579cd4edfb4a2fae3bb11eb75f7824c.js:197:13164
    at async Promise.all (index 0)

Do you have advise how to fix it ?

**Comment by vaibhavgg** [comment]
Hi,

We are getting the same issue. 
Can you please let us know how you were able to resolve it?

**Comment by dperk6** [comment]
This issue was resolved without our input... I wonder if this is related to the Graph Toolkit dependency? Have you installed? 

This solution uses Microsoft Graph Toolkit v3. You must install the [sppkg package from Microsoft](https://github.com/microsoftgraph/microsoft-graph-toolkit/releases/tag/v3.1.0) before installing this app.

**Comment by vaibhavgg** [comment]
We tried installing the Graph toolkit in the project directory and rebuilt, and deployed it. But, still getting same error - 

**Something went wrong
If the problem persists, contact the site administrator and give them the information in Technical Details.
TECHNICAL DETAILS
ERROR:
Cannot read properties of undefined (reading 'id')

CALL STACK:
TypeError: Cannot read properties of undefined (reading 'id')
    at https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_c857010531473be3b19536fdffb95dfb.js:198:10988
    at new Promise (<anonymous>)
    at e.loadComponent (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_c857010531473be3b19536fdffb95dfb.js:198:10956)
    at https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_c857010531473be3b19536fdffb95dfb.js:198:13164
    at async Promise.all (index 0)**

**Comment by dperk6** [comment]
API permissions perhaps? Did you confirm in the admin center?

Also, did you build it yourself or use the sppkg file in the releases?

**Comment by derynj** [comment]
Hi,
Thanks for the project it's the best I have seen so far. I am having the same issue. Installed the sppkg from Microsoft before installing this app. How did you guys fix this issue?

**Comment by dperk6** [comment]
Did you approve the API permissions in SharePoint Admin Center?

**Comment by derynj** [comment]
Hi,
I approved all 3 API permissions when requested when installing the SP package. (User.Read.All, Chat.ReadWrite.All, Group.Read.All)

Works locally on SP workbench, but when deployed to SP it shows the above error mentioned.

**Comment by dperk6** [comment]
Sorry for the issues. I'm having trouble reproducing the problem on my end... can @cerberuscgn assist? How were you able to resolve this?

**Comment by dperk6** [comment]
@derynj did you rebuild the project or use sppkg file? I've had similar issues with other SPFx solutions with dependency mismatches.

**Comment by derynj** [comment]
@dperk6 Thanks for the update. 

- I ran npm i @microsoft/mgt@latest before generating the SP package file. 
- Updated my serve.json to match my SP env
- Ran yarn dev 
- Yarn build to see if any errors.
- yarn package
- Deployed the package to my app catalog and granted the perms

**Comment by dperk6** [comment]
Sounds like a dependency issue. The latest version of mgt is 4.2 but this project uses 3.1. The mgt release linked in the README file (sppkg file) is 3.1. 4.2 *might* work but it'll require you to uninstall mgt 3.1 from your app catalog and replace it. Also keep in mind there's another package (mgt-spfx) that is version 3.1. It looks like Microsoft has replaced this package with mgt-spfx-utils. I haven't looked into any of this in depth but there's a high likelihood it'll require code changes. I'll put an updated version on my to do list.

For now, my recommendation is to just use the staff directory sppkg file in the releases in this repo.
